### ISSUE TITLE
Please help to see how to support automatic update of password of aws secretsmanager, and identify the VersionStages: AWSCURRENT field, which can automatically obtain the latest Versionid without manual configuration

### ISSUE THREAD

**Issue by g1938809124** [mumoshu/aws-secret-operator#51] opened 2022-05-06 02:24 UTC
Please help to see how to support automatic update of password of aws secretsmanager, and identify the VersionStages: AWSCURRENT field, which can automatically obtain the latest Versionid without manual configuration

All previous versions supported these features  （image: 3onaco/aws-secret-operator:0.2.4  ）eks Version:"v1.19.15-eks"

Now the latest version does not support it, can you help to support  automatic update of password of aws secretsmanager,?（image: image mumoshu/aws-secret-operator:0.4.0）eks GitVersion:"v1.22.5"

apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: AWSSecretPrd
  namespace: prd
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      VersionStages: AWSCURRENT
      secretId: vdev/eks/n8n/app-credentials

thanks

**Comment by mumoshu** [comment] 2022-05-08 22:29
We've never had the support for specifying `VersionStages` so perhaps you were just rereading the secret after an re-reconcilation of AWSSecret into a Secret?

The operator reconciles an AWSSecret when it has any changes or the "resync period" elapsed.
Would you try holding on a bit so that it will eventually resync?
Wee might also need an another command-line flag to make the resync period configurable 🤔 

Anyway, my recommendation is just keep updating versionId explicitly, so that the timing is more controllable.

Also, how do you consume the generated Secert?

**Comment by mumoshu** [comment] 2022-06-21 05:47
Probably this is a duplicate of #45. Let's discuss it there. Thanks!

**Closed by mumoshu** 2022-06-21 05:47 UTC
